# Generated by Django 2.2.12 on 2023-04-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipe', models.CharField(max_length=255)),
                ('nom_entraineur', models.CharField(max_length=255)),
                ('joueurs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tournoi', models.CharField(max_length=255)),
                ('nb_poules', models.IntegerField()),
                ('nb_equipes_poule', models.IntegerField()),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('dates', models.DateTimeField(blank=True, null=True)),
                ('liste_equipes', models.ManyToManyField(to='AppTournois.Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Poule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poule', models.IntegerField()),
                ('equipes', models.ManyToManyField(to='AppTournois.Equipe')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTournois.Tournoi')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('score', models.CharField(blank=True, max_length=255, null=True)),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_joues1', to='AppTournois.Equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_joues2', to='AppTournois.Equipe')),
                ('numero_poule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppTournois.Poule')),
            ],
        ),
    ]
