# Generated by Django 2.2.12 on 2023-04-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTournois', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='score_equipe1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_equipe2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe1', to='AppTournois.Equipe'),
        ),
        migrations.AlterField(
            model_name='match',
            name='equipe2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe2', to='AppTournois.Equipe'),
        ),
    ]
