# Generated by Django 2.2.12 on 2023-04-17 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTournois', '0002_auto_20230416_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_equipe2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
