# Generated by Django 2.2.12 on 2023-04-17 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTournois', '0003_auto_20230417_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_equipe1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
