# Generated by Django 4.2 on 2023-04-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTournois', '0004_alter_commentaire_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='match',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='match_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='AppTournois.match'),
        ),
    ]
