# Generated by Django 4.2 on 2023-04-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTournois', '0005_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='match',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
