# Generated by Django 4.2 on 2023-04-17 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppTournois', '0006_match_commentaire_alter_commentaire_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentairess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(blank=True, max_length=200, null=True)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='match',
            old_name='commentaire',
            new_name='commentairess',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
