# Generated by Django 4.2 on 2023-04-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTournois', '0007_alter_commentaire_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaire', to='AppTournois.match'),
        ),
    ]
