# Generated by Django 4.2 on 2023-04-17 20:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppTournois', '0007_commentairess_rename_commentaire_match_commentairess_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commentairess',
            new_name='commentaire',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='commentairess',
            new_name='commentaire',
        ),
    ]
